version: '3.8'

services:
  web:
    container_name: interface
    build: .
    env_file:
      - .env
      - secret.env
    ports:
      - 8181:8181
    volumes:
      - .:/usr/src/app
    command: go run cmd/main.go -b 0.0.0.0
    networks:
      - postgres 
    depends_on:
      - data_base
  postgres:
    container_name: data_base
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
  #    PGDATA: "/var/lib/postgresql/data/pgdata"
  #  volumes:
  #    - ./:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
    # https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_USER_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    #volumes:
    #  - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres    

# https://habr.com/ru/post/578744/
networks:
  postgres:
    driver: bridge