# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
 
    runs-on: ubuntu-latest
    env:
      HOST: root@${{secrets.PROMO_POSTER_IP}}
      DEPLOY_DIRECTORY: /root/apps/propmo-poster  
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23
    - name: Build app
      run: |
        go mod download
        go build -o promo-poster ./main.go
    - name: Deploy to VM
      run: |
          sudo apt-get install -y ssh 
          sudo apt-get install rsync -y
          echo "$DEPLOY_SSH_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} "mkdir -p ${{ env.DEPLOY_DIRECTORY }}"
          rsync -avz -e 'ssh -i deploy_key.pem -o StrictHostKeyChecking=no' --exclude='.git' ./ ${{ env.HOST }}:${{ env.DEPLOY_DIRECTORY }}
      env:
          DEPLOY_SSH_KEY: ${{ secrets.PROMO_POSTER_KEY }}
    - name: Remove old systemd service file
      run: |
        ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} "rm -f /etc/systemd/system/promo-poster"
    - name: List workspace contents
      run: |
          echo "Listing deployment folder (${{ github.workspace }}/deployment) contents:"
          ls -la ${{ github.workspace }}/deployment
    - name: Copy systemd service file
      run: |
          scp -i deploy_key.pem -o StrictHostKeyChecking=no ${{ github.workspace }}/deployment/promo-poster.service ${{ env.HOST }}:/tmp/promo-poster.service
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} "mv /tmp/promo-poster.service /etc/systemd/system/promo-poster.service"
    - name: Start application
      run: |
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} "systemctl daemon-reload && systemctl restart promo-poster.service"
